name: GitHub Pages CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      G_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Build website
        run: sudo -E bash -ex buildWebsite.sh
